#include "dictionary/core_dict.h"

#include <string>
#include <string_view>
#include <vector>

// v0.8: Only closed class entries (function words)
// Open class words (nouns, verbs, adjectives, adverbs) are handled by:
// - Analysis engine (conjugation generation)
// - L2 dictionary (core.dic)
#ifdef __EMSCRIPTEN__
#include "dictionary/entries/packed_core_entries.h"
#else
#include "dictionary/entries/auxiliaries.h"
#include "dictionary/entries/compound_particles.h"
#include "dictionary/entries/conjunctions.h"
#include "dictionary/entries/determiners.h"
#include "dictionary/entries/formal_nouns.h"
#include "dictionary/entries/interjections.h"
#include "dictionary/entries/particles.h"
#include "dictionary/entries/pronouns.h"
#endif
#include "normalize/utf8.h"

namespace suzume::dictionary {

namespace {

#ifndef __EMSCRIPTEN__
void stableSortEntrySpecs(std::vector<entries::EntrySpec>& entry_specs) {
  std::vector<entries::EntrySpec> buffer(entry_specs.size());
  for (size_t width = 1; width < entry_specs.size(); width *= 2) {
    for (size_t left = 0; left < entry_specs.size(); left += width * 2) {
      const size_t middle = left + width < entry_specs.size() ? left + width : entry_specs.size();
      const size_t right = middle + width < entry_specs.size() ? middle + width : entry_specs.size();
      size_t lhs = left;
      size_t rhs = middle;
      size_t output = left;
      while (lhs < middle && rhs < right) {
        if (std::string_view(entry_specs[rhs].surface) < std::string_view(entry_specs[lhs].surface)) {
          buffer[output++] = entry_specs[rhs++];
        } else {
          buffer[output++] = entry_specs[lhs++];
        }
      }
      while (lhs < middle) {
        buffer[output++] = entry_specs[lhs++];
      }
      while (rhs < right) {
        buffer[output++] = entry_specs[rhs++];
      }
    }
    entry_specs.swap(buffer);
  }
}
#endif

}  // namespace

CoreDictionary::CoreDictionary() {
  initializeEntries();
}

void CoreDictionary::initializeEntries() {
  // ==========================================================================
  // v0.8: Layer 1 only - Closed class entries (function words)
  // ==========================================================================
  // These are grammatically fixed sets with known upper bounds.
  // They rarely change and are tied to language structure.
  //
  // Open class words (nouns, verbs, adjectives, adverbs) are:
  // - Generated by analysis engine (verb/adjective conjugation)
  // - Loaded from L2 dictionary (core.dic) if available
#ifdef __EMSCRIPTEN__
  const auto packed_entries = entries::getPackedCoreEntries();
  const char* string_data = reinterpret_cast<const char*>(packed_entries.stringData());
  entries_.reserve(packed_entries.size());
  for (const auto& entry : packed_entries) {
    entries_.push_back({string_data + entry.surface_offset, static_cast<core::PartOfSpeech>(entry.pos),
                        static_cast<core::ExtendedPOS>(entry.extended_pos), string_data + entry.lemma_offset});
  }
#else
  auto particles = entries::getParticleEntries();
  auto compound_particles = entries::getCompoundParticleEntries();
  auto auxiliaries = entries::getAuxiliaryEntries();
  auto conjunctions = entries::getConjunctionEntries();
  auto determiners = entries::getDeterminerEntries();
  auto pronouns = entries::getPronounEntries();
  auto formal_nouns = entries::getFormalNounEntries();
  auto interjections = entries::getInterjectionEntries();

  const size_t entry_count = particles.size() + compound_particles.size() + auxiliaries.size() + conjunctions.size() +
                             determiners.size() + pronouns.size() + formal_nouns.size() + interjections.size();

  // Sort the trivial source records before constructing owned strings. This
  // keeps all materialization in one loop and makes the stable-sort
  // instantiation much smaller than sorting DictionaryEntry objects.
  std::vector<entries::EntrySpec> entry_specs;
  entry_specs.reserve(entry_count);
  auto addSpecs = [&entry_specs](entries::EntrySpecRange source) {
    entry_specs.insert(entry_specs.end(), source.begin(), source.end());
  };

  addSpecs(particles);
  addSpecs(compound_particles);
  addSpecs(auxiliaries);
  addSpecs(conjunctions);
  addSpecs(determiners);
  addSpecs(pronouns);
  addSpecs(formal_nouns);
  addSpecs(interjections);

  // Sort entries by surface for Double-Array compatibility while preserving
  // the registration order of duplicate surfaces.
  stableSortEntrySpecs(entry_specs);

  entries_.reserve(entry_count);
  for (const auto& entry : entry_specs) {
    entries_.push_back({entry.surface, entry.pos, entry.extended_pos, entry.lemma});
  }
#endif

  // Build Double-Array trie
  buildTrie();
}

void CoreDictionary::buildTrie() {
  if (entries_.empty()) {
    return;
  }

  // Build unique keys with first occurrence index. Entries are already sorted,
  // so a comparison with the previous item is sufficient.
  std::vector<std::string> keys;
  std::vector<int32_t> values;
  keys.reserve(entries_.size());
  values.reserve(entries_.size());
  for (size_t idx = 0; idx < entries_.size(); ++idx) {
    if (idx == 0 || entries_[idx].surface != entries_[idx - 1].surface) {
      keys.push_back(entries_[idx].surface);
      values.push_back(static_cast<int32_t>(idx));
    }
  }

  // Build the Double-Array trie
  trie_.build(keys, values);
}

std::vector<LookupResult> CoreDictionary::lookup(std::string_view text, size_t start_pos) const {
  std::vector<LookupResult> results;

  if (entries_.empty() || start_pos >= text.size()) {
    return results;
  }

  // Use Double-Array common prefix search
  auto trie_results = trie_.commonPrefixSearch(text, start_pos);

  for (const auto& tres : trie_results) {
    if (tres.value < 0 || static_cast<size_t>(tres.value) >= entries_.size()) {
      continue;
    }

    size_t first_idx = static_cast<size_t>(tres.value);
    const std::string& matched_surface = entries_[first_idx].surface;

    // Collect all entries with the same surface (consecutive in sorted array)
    for (size_t idx = first_idx; idx < entries_.size(); ++idx) {
      if (entries_[idx].surface != matched_surface) {
        break;
      }

      LookupResult result{};
      result.entry_id = static_cast<uint32_t>(idx);
      // Convert byte length to character count
      result.length = normalize::utf8Length(text.substr(start_pos, tres.length));
      result.entry = &entries_[idx];
      results.push_back(result);
    }
  }

  return results;
}

const DictionaryEntry* CoreDictionary::getEntry(uint32_t idx) const {
  if (idx < entries_.size()) {
    return &entries_[idx];
  }
  return nullptr;
}

const DictionaryEntry* CoreDictionary::lookupExact(std::string_view surface, core::PartOfSpeech pos) const {
  const int32_t first_idx = trie_.exactMatch(surface);
  if (first_idx < 0 || static_cast<size_t>(first_idx) >= entries_.size()) {
    return nullptr;
  }

  for (size_t idx = static_cast<size_t>(first_idx); idx < entries_.size() && entries_[idx].surface == surface; ++idx) {
    if (pos == core::PartOfSpeech::Unknown || entries_[idx].pos == pos) {
      return &entries_[idx];
    }
  }
  return nullptr;
}

}  // namespace suzume::dictionary
